# Generated by Django 4.2.6 on 2023-10-10 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('section_order', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('profile_pic', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='productview',
            options={'verbose_name_plural': 'LastViewedProduct'},
        ),
    ]
