# Generated by Django 4.2.6 on 2023-10-10 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product_view', '0002_user_alter_productview_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('shop_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.BigIntegerField()),
                ('category_id', models.CharField(max_length=255)),
                ('subcategory_id', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('admin_status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('blacklisted', 'Blacklisted')], default='pending', max_length=20)),
                ('is_deleted', models.CharField(choices=[('active', 'Active'), ('temporary', 'Temporary')], default='active', max_length=20)),
                ('image_id', models.CharField(max_length=255)),
                ('rating_id', models.BigIntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('currency', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
