# Generated by Django 4.2.6 on 2023-10-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_view', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
