# Generated by Django 4.2.6 on 2023-10-11 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='parent_category_id',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productsubcategory',
            name='status',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='productsubcategory',
            table='product_sub_category',
        ),
    ]
