# Generated by Django 4.2.6 on 2023-10-09 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('parent_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketPlace.productcategory')),
            ],
            options={
                'verbose_name_plural': 'ProductSubCategories',
                'db_table': 'product_subcategory',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MarketPlace.productsubcategory'),
        ),
    ]
