# Generated by Django 4.2.6 on 2023-10-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
