name: Zuri Market Place API Github Action Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.x]

    steps:
      - uses: actions/checkout@v3
      - name: Set Python Version ${{ matrix.python-version }}
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create .env file
        run: |
          echo "DB_NAME=${{ secrets.ENV_DB_NAME }}" >> .env
          echo "DB_HOST=${{ secrets.ENV_DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.ENV_DB_PORT }}" >> .env
          echo "DB_USER=${{ secrets.ENV_DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.ENV_DB_PASSWORD }}" >> .env
          echo "DB_NAME_TWO=${{ secrets.ENV_DB_NAME_TWO }}" >> .env
          echo "DB_HOST_TWO=${{ secrets.ENV_DB_HOST_TWO }}" >> .env
          echo "DB_PORT_TWO=${{ secrets.ENV_DB_PORT_TWO }}" >> .env
          echo "DB_USER_TWO=${{ secrets.ENV_DB_USER_TWO }}" >> .env
          echo "DB_PASSWORD_TWO=${{ secrets.ENV_DB_PASSWORD_TWO }}" >> .env

      - name: Lint with flake8
        run: |
          flake8 .
      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run the app
        run: |
          python manage.py runserver &

      # Add a sleep command to give the server some time to start before stopping it
      - name: Wait for the app to start
        run: sleep 10s

      # Use pkill to stop the Django server process
      - name: Stop the app
        run: pkill -f "python manage.py runserver"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: pull changes and build
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST_STAGING }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/devops/romulus_zuri_backend/Team_Romulus_Zuri_MarketPlace
            git fetch origin
            git pull origin dev

      - name: restart server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST_STAGING }}
          username: ${{ secrets.USERNAME2 }}
          password: ${{ secrets.PASSWORD2 }}
          port: ${{ secrets.PORT }}
          script: |
            systemctl restart romulus_zuri_backend
